### ISSUE TITLE
Stale chart files can cause repeated udates

### ISSUE THREAD

**Issue by transmitterdan** [nohal/chartdldr_pi#63]
Apparently sometimes a new .zip file from NOAA or ACE will not replace every file. I think this can happen when a complete new ENC file is created. Then the update files are not in the .zip file. The old update files are still in the chart folder. These "old" files trick the downloader into thinking the chart is out of date.

A possible solution is to delete all filles in the folder prior to unzipping the just downloaded .zip file.

**Comment by transmitterdan** [comment]
Another possible solution might be to "touch" all the files in the folder after unzipping.

**Comment by nohal** [comment]
Do we have some example of such a file? I would like to see what's in there.
Anyway, we basically have two options
- Try to fight with the file timestamps
- Create a file in the chart directory holding the chart number and last update timestamp (while still fall back to the chart file timestamps when the data is not available, to let the user to manage his preexisting chart portfolio)
  I'm kind of inclined to the second option for a simple reason - a lot of non-US chart sources are a total mess and we already now replace the brain of the publisher with `reference_file`, which we could avoid.

**Comment by transmitterdan** [comment]
Pavel,

I think one would have to have a previous version of the .zip file to see this problem. Unfortunately, I don’t have the previous .zip file.

This link:

http://ienccloud.us/ienc/web/iencu37productsdownload.cfm?mode=0660&cell=U37TB176

is one I have an issue with right now. This is what is in my chart folder:

```
dan@dan-VirtualBox ~/.opencpn/Charts/ENC/US_INLAND/U37TB176 $ ls -l
total 3056
-rw-r--r-- 1 dan dan    1187 Mar  2 00:00 CATALOG.031
-rw-r--r-- 1 dan dan 2852839 Mar  2 00:00 U37TB176.000
-rw-r--r-- 1 dan dan    2222 Feb  3 00:00 U37TB176.001
-rw-r--r-- 1 dan dan   39820 Mar  2 00:00 U3BW219001.JPG
-rw-r--r-- 1 dan dan   35960 Mar  2 00:00 U3BW265201.JPG
-rw-r--r-- 1 dan dan   41458 Mar  2 00:00 U3BW267801.JPG
-rw-r--r-- 1 dan dan  101043 Mar  2 00:00 U3TB020401.JPG
-rw-r--r-- 1 dan dan   10166 Mar  2 00:00 U3TB176NP1.TXT
-rw-r--r-- 1 dan dan   27841 Mar  2 00:00 U3TB219001.JPG
```

Note that U37TB176.001 is not in the .zip file any longer.
I also worry that this stale file might cause some problems with OpenCPN. Is the ENC file format smart enough so that it will ignore these old stale update files?

**Comment by transmitterdan** [comment]
After thinking about this for a bit I think we could "archive" the existing files into a .backup directory. Then we can clean the target directory and unzip the new file. If all goes well then we can delete the .backup directory and its files. If something goes wrong in the unzip process we can restore the files from .backup.

If we don't unzip into a clean folder each time we will have issues with stale files hanging around forever I think.

**Comment by nohal** [comment]
Hmmm... It could cause problems, as in theory the updates can just contain .001, .002, leading to loss of the base cell.
The .001 update should now fail to apply on the base cell (You should see it in the logfile)

**Comment by transmitterdan** [comment]
The log file is here:

https://drive.google.com/file/d/0B-_IyvPyKP6yQmY0VVlzYWpCSEk/view?usp=sharing

I did not see any error message about that particular ENC chart. The U37TB176.001 file is not mentioned by O but the .000 file is mentioned.

**Comment by transmitterdan** [comment]
Pavel,

I tested this fix today on Windows XP and Linux Mint. These are on two different virtual machines where I can build and test. I think this problem is fixed as far as I can tell. I know this was a lot of work to change things around. Well done.

Dan

**Comment by transmitterdan** [comment]
Pavel,

I am seeing a problem with the Brazil RNC charts. My Windows XP system says there are 253 new charts in the Brazil catalog. When I tell it to download all new charts, using right click select all new then download marked charts, it finishes with an error that 1 of 253 could not be downloaded. Then it says there are 253 new charts again. I have run it 3 times now and it does the same thing every time. I don’t know why it thinks there are 253 new charts as it seems I have all (or nearly all) of the .BSB and .KAP files in the Brazil chart folder.

Dan

**Comment by nohal** [comment]
Should be fixed in master now, it is because of the picture files containing spaces

**Comment by transmitterdan** [comment]
Problem remains the same as before on Windows XP. I pulled from git the latest and it now shows version 0.9 so I think I have the latest sources.

**Comment by nohal** [comment]
Grrr, I forgot to push to github, the fix is in f042556
Note that you have to perform some operation on the chart source or delete chartdldr_pi.dat manually so that it "does something"...

Sorry

**Comment by transmitterdan** [comment]
Pavel,

Got the fix and it seem so ok to me now. One problem remains with the Brazil catalog. I cannot download a file 1703.zip with the downloader. Not sure if there is a problem with the catalog xml file or the Brazil web site. This is the only chart that fails to download. Am testing on Windows XP.

Dan

**Comment by nohal** [comment]
The zip file for 1703 currently does not exist on the server, nothing we can do about it...

**Comment by transmitterdan** [comment]
Ok, then all is well. Will you post new installers on sourceforge and so forth?

**Comment by nohal** [comment]
If noone complains about anything else, I will release 1.0 tonight or tomorrow.

**Comment by transmitterdan** [comment]
Pavel,

I tested from git on Linux and Windows a few hours ago. Found no issues. 

Best regards,
Dan
